services:
  - type: web
    name: candidate-search
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_GITHUB_TOKEN
        sync: false
