services:
  - type: web
    name: candidate-search
    env: node
    plan: free
    buildCommand: |
      npm ci
      npm install vite --save-dev
      npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_GITHUB_TOKEN
        sync: false
    buildFilter:
      paths:
        - .
