services:
  - type: web
    name: candidate-search
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_GITHUB_TOKEN
        sync: false
